---
title: "Final Project Slides"
format: revealjs
---

```{r}
#| echo: false
#| output: false
#| warning: false
library(tidyverse)
scoobydoo <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-07-13/scoobydoo.csv')
df <- scoobydoo |> select(2, 5, 13, 16, 18:41, 48, 54, 55, 58, 59, 62, 65, 17)
df <- df |> mutate(split_up = fct_recode(split_up, No = "0", Yes = "1", Yes = "2")) |>
  mutate(trap_work_first = if_else(is.na(trap_work_first),                    
                                       "NULL", trap_work_first)) |>
  mutate(trap_work_first = fct_recode(trap_work_first, No = "FALSE", Yes = "TRUE", "NA" = "NULL")) |>
  mutate(culprit_gender = fct_collapse(culprit_gender,
                                           Male = c("Male", "Male,Male",
                                                    "Male,Male,Male",
                                                    "Male,Male,Male,Male",
                                                    "Male,Male,Male,Male,Male"),
                                           Female = c("Female", "Female,Female"),
                                           "Male and Female" = c("Female,Female,Male",
                                                                 "Female,Male",
                                                                 "Female,Male, Male",
                                                         "Female,Male,Female,Male,Male",
                                                                 "Female,Male,Male",
                                                                "Female,Male,Male,Male",
                                                                 "Male,Female",                                                      "Male,Female,Female,Male,Male,Male,Female",
                     "Male,Female,Female,Male,Male,Male,Female,Female,Male,Male,Female",
                                                                 "Male,Female,Male",
                                                             "Male,Female,Male,Female",
                                                   "Male,Female,Male,Female,Male,Male",
                                                                 "Male,Male,Female",
                                                          "Male,Male,Female,Male,Male",
                                                               "Male,Male,Male,Female",
                          "Male,Male,Male,Male,Male,Male,Female,Male,Male,Male,Male"))) |>
  mutate(monster_type = fct_collapse(monster_type,
                                         "Ancient" = c("Ancient", "Ancient,Ancient",
                                                       "Ancient,Animal",   "Ancient,Ghost,Extraterrestrial,Animal,Disguised,Ghost,Possessed Object,Magician,Magician,Ghost,Undead,Possessed Object,",
                                                       "Ancient,Possessed", 
                                                       "Ancient,Possessed Object"),
                                         "Animal" = c("Animal", "Animal,Ancient",
                                                      "Animal,Ancient,Ancient,Mechanical,Plant",
                                                      "Animal,Animal",
                                                      "Animal,Animal,Animal",
                                                      "Animal,Animal,Animal,Animal",
                                                      "Animal,Animal,Mythical,Possessed Object,Possessed Object,Ghost,Undead",
                                                      "Animal,Disguised",
                                                      "Animal,Mechanical",
                                                      "Animal,Plant",
                                                      "Animal,Undead",
                                                      "Animal,Undead,Disguised,Animal,Disguise,Ghost,Ghost,Animal",
                                                      "Animal,Undead,Undead"),
                                         "Disguised" = c("Disguised", "Disguised,Animal",
                                                         "Disguised,Animal,Possessed Object,Possessed Object,Possessed Object,Ancient,Possessed Object,Undead,Ghost,Undead,Undead",
                                                         "Disguised,Disguised",
                                                         "Disguised,Disguised,Disguised,Disguised",
                                                         "Disguised,Skeleton",
                                                         "Disguised,Undead,Animal,Animal",
                                                         "Disguised,Undead,Undead"),
                                         "Extraterrestrial" = c("Extraterrestrial",
                                                                "Extraterrestrial,Animal,Extraterrestrial",
                                                                "Extraterrestrial,Extraterrestrial",
                                                                "Extraterrestrial,Extraterrestrial,Extraterrestrial"),
                                         "Ghost" = c("Ghost", "Ghost,Ancient", "Ghost,Animal",
                                                     "Ghost,Disguised",                   "Ghost,Disguised,Undead,Disguised,Animal,Animal,Animal,Ancient,Disguised",
                                                     "Ghost,Ghost",
                                                     "Ghost,Ghost,Animal","Ghost,Ghost,Ghost",
                                                     "Ghost,Ghost,Ghost,Ghost",
                                                     "Ghost,Ghost,Ghost,Ghost,Mythical",
                                                     "Ghost,Ghost,Magician,Ghost", 
                                                     "Ghost,Ghost,Mythical",
                                                     "Ghost,Ghost,Undead,Animal,Animal",
                                                     "Ghost,Ghost,Undead,Undead,Possessed Object,Ghost",
                                                     "Ghost,Mythical","Ghost,Plant,Animal",
                                                     "Ghost,Possessed Object","Ghost,Undead",
                                                     "Ghost,Undead,Undead",
                                                     "Ghost,Undead,Undead,Undead,Animal,Animal,Animal"),
                                         "Magician" = c("Magician", "Magician,Animal",
                                                        "Magician,Ghost,Ghost",
                                                        "Magician,Ghost,Plant,Plant,Animal",
                                                        "Magician,Magician,Magician,Magician",
                                                        "Magician,Plant,Magician,Animal",
                                                        "Magician,Possessed Object",
                                                        "Magician,Possessed Object,Mythical,Demon"),
                                         "Mechanical" = c("Mechanical", "Mechanical,Ghost",
                                                          "Mechanical,Mechanical",
                                                          "Mechanical,Mechanical,Mechanical",
                                                          "Mechanical,Mechanical,Mechanical,Mechanical,Mechanical",
                                                          "Mechanical,Super-Villain,Animal,Mythical",    "Mechanical,Super-Villain,Disguised,Disguised,Super-Villain,Super-Villain,Super-Villain,Mechanical"),
                                         "Mythical" = c("Mythical", "Mythical,Ancient", 
                                                        "Mythical,Animal,Magician",
                                                        "Mythical,Ghost,Ghost",
                                                        "Mythical,Ghost,Ghost,Ghost",
                                                        "Mythical,Ghost,Ghost,Undead,Undead,Undead,Undead",
                                                        "Mythical,Mythical",
                                                        "Mythical,Mythical,Mythical,Mythical,Possessed Object,Possessed Object,Possessed Object,Possessed Object,Possessed Object,Animal",
                                                        "Mythical,Mythical,Mythical,Undead,Mythical,Mythical",
                                                        "Mythical,Plant,Plant,Mythical,Animal,Animal",
                                                        "Mythical,Undead"),
                                         "Plant" = c("Plant", "Plant,Animal,Animal,Magician",
                                                     "Plant,Plant", "Plant,Possessed Object"),
                                         "Possessed Object" = c("Possessed Object", 
                                                                "Possessed Object,Ghost",
                                                                "Possessed Object,Ghost,Ghost",
                                                                "Possessed Object,Magician",
                                                                "Possessed Object,Mythical,Animal,Animal,Animal",
                                                                "Possessed Object,Possessed Object",
                                                                "Possessed Object,Possessed Object,Possessed Object"),
                                         "Super-Villain" = c("Super-Villain", 
                                                             "Super-Villain,Disguised,Disguised",
                                                             "Super-Villain,Disguised,Disguised,Disguised,Disguised,Disguised,Disguised,Disguised,Disguised,Disguised,Super-Villain",
                                                             "Super-Villain,Disguised,Disguised,Disguised,Disguised,Disguised,Disguised,Disguised,Disguised,Disguised,Super-Villain,Super-Villain,Super-Villain",
                                                             "Super-Villain,Disguised,Disguised,Disguised,Disguised,Disguised,Disguised,Disguised,Super-Villain",                                   "Super-Villain,Disguised,Disguised,Disguised,Disguised,Disguised,Disguised,Disguised,Disguised,Super-Villain,Super-Villain,Super-Villain",                                      "Super-Villain,Disguised,Disguised,Disguised,Disguised,Disguised,Disguised,Disguised,Disguised,Super-Villain",
                                                             "Super-Villain,Disguised,Disguised,Disguised,Disguised,Disguised,Super-Villain",
                                                             "Super-Villain,Disguised,Disguised,Super-Villain",
                                                             "Super-Villain,Mechanical,Disguised,Super-Villain",
                                                             "Super-Villain,Super-Villain,Disguised,Disguised,Super-Villain,Super-Villain",
                                                             "Super-Villain,Super-Villain,Super-Villain",
                                                             "Super-Villain,Super-Villain,Super-Villain,Disguised,Disguised,Disguised",
                                                             "Super-Villain,Super-Villain,Super-Villain,Super-Villain,Disguised",
                                                             "Super-Villain,Super-Villain,Super-Villain,Super-Villain,Super-Villain,Super-Villain,Super-Villain,Super-Villain,Super-Villain,Super-Villain,Super-Villain",
                                                             "Super-Villain,Super-Villain,Super-Villain,Disguised,Disguised,Disguised,Disguised,Disguised,Disguised,Disguised,Disguised",
                                                             "Super-Villain,Disguised,Disguised,Disguised,Disguised,Disguised,Disguised,Disguised,Disguised,Disguised,Disguised,Disguised,Disguised,Disguised,Dr. Trebal",
                                                             "Super-Villain,Disguised,Disguised,Disguised,Disguised,Disguised,Disguised,Disguised,Disguised,Disguised,Disguised,Dr. Trebal,Super-Villain",
                                                             "Super-Villain,Disguised,Disguised,Disguised,Disguised,Disguised,Disguised,Disguised,Disguised,Disguised, Disguised, Disguised,Super-Villain",
                                                             "Super-Villain,Super-Villain,Super-Villain,Disguised,Super-Villain,Super-Villain,Super-Villain",
                                                             "Super-Villain,Super-Villain,Mechanical,Super-Villain,Super-Villain,Disguised,Disguised",
                                                             "Super-Villain,Super-Villain,Disguised,Disguised,Super-Villain,Super-Villain,Disguised,Disguised,Disguised",
                                                             "Super-Villain,Super-Villain,Disguised,Disguised,Disguised,Disguised,Disguised,Super-Villain",
                                                             "Super-Villain,Super-Villain,Disguised,Disguised,Disguised,Disguised,Disguised,Disguised,Super-Villain,Super-Villain",
                                                             "Super-Villain,Disguised,Disguised,Disguised,Super-Villain,Super-Villain,Super-Villain,Super-Villain,Super-Villain",
                                                             "Super-Villain,Disguised,Disguised,Super-Villain,Super-Villain,Super-Villain,Animal,Animal,Undead,Undead,Undead,Animal",
                                                             "Super-Villain,Disguised,Disguised,Disguised,Super-Villain,Super-Villain,Super-Villain,Super-Villain,Super-Villain",
                                                             "Super-Villain,Disguised,Disugised,Disguised,Super-Villain,Super-Villain,Super-Villain,Animal,Animal"),
                                         "Undead" = c("Undead", "Undead,Animal", "Undead,Animal,Animal,Animal,Animal",
                                                      "Undead,Animal,Undead", "Undead,Ghost,Ghost,Ghost,Ancient,Ghost,Ghost",
                                                      "Undead,Ghost,Ghost,Ghost,Plant", "Undead,Ghost,Undead,Undead",
                                                      "Undead,Magician", "Undead,Undead", "Undead,Undead,Animal",
                                                      "Undead,Undead,Mythical,Mythical,Magician,Mythical,Mythical,Mythical",
                                                      "Undead,Undead,Plant,Animal",
                                                      "Undead,Undead,Undead", "Undead,Undead,Undead,Animal",
                                                      "Undead,Undead,Undead,Undead",
                                                      "Undead,Undead,Undead,Undead,Undead,Undead,Undead,Undead",
                                                      "Undead,Animal,Undead,Undead,Magician,Magician,Undead,Undead,Possessed Object,Undead,Disfigured,Disfigured,Animal,Disguised,Insect,Insect,Possessed Object,Animal,Plant"))) |>
  mutate(number_of_snacks = fct_collapse(number_of_snacks,
                                             "2" = c("2", "a couple"),
                                             "3" = c("3", "several"),
                                             "3 boxes" = c("3 boxes", "several boxes")))

caught_df <- df |> select(1, 2, 3, 4, 5, 6, 7, 8 , 9, 26, 27, 28, 29, 30, 31, 36) |> 
  mutate(caught_fred = as.factor(caught_fred)) |>
  mutate(caught_fred = if_else(caught_fred == "TRUE",
                               true = "Fred",
                               false = "0")) |>
  mutate(caught_daphnie = as.factor(caught_daphnie)) |>
  mutate(caught_daphnie = if_else(caught_daphnie == "TRUE",
                               true = "Daphnie",
                               false = "0")) |>
  mutate(caught_velma = as.factor(caught_velma)) |>
  mutate(caught_velma = if_else(caught_velma == "TRUE",
                               true = "Velma",
                               false = "0")) |>
  mutate(caught_shaggy = as.factor(caught_shaggy)) |>
  mutate(caught_shaggy = if_else(caught_shaggy == "TRUE",
                               true = "Shaggy",
                               false = "0")) |>
  mutate(caught_scooby = as.factor(caught_scooby)) |>
  mutate(caught_scooby = if_else(caught_scooby == "TRUE",
                               true = "Scooby",
                               false = "0")) |>
  mutate(caught_other = as.factor(caught_other)) |>
  mutate(caught_other = if_else(caught_other == "TRUE",
                               true = "Other",
                               false = "0")) |> 
  mutate(caught_not = as.factor(caught_not)) |>
  mutate(caught_not = if_else(caught_not == "TRUE",
                               true = "Not Caught",
                               false = "0")) |>
  pivot_longer(cols = (5:11), names_to = "who", values_to = "caught_by") |>
  separate(col = who, into = c("caught", "who"), sep = "_") |>
  mutate(caught_by = if_else(caught_by!=0, 1, 0))

captured_df <- df |> select(1:4, 10:14, 26:31, 36) |> 
  mutate(captured_fred = as.factor(captured_fred)) |>
  mutate(captured_fred = if_else(captured_fred == "TRUE",
                               true = "Fred",
                               false = "0")) |>
  mutate(captured_daphnie = as.factor(captured_daphnie)) |>
  mutate(captured_daphnie = if_else(captured_daphnie == "TRUE",
                               true = "Daphnie",
                               false = "0")) |>
  mutate(captured_velma = as.factor(captured_velma)) |>
  mutate(captured_velma = if_else(captured_velma == "TRUE",
                               true = "Velma",
                               false = "0")) |>
  mutate(captured_shaggy = as.factor(captured_shaggy)) |>
  mutate(captured_shaggy = if_else(captured_shaggy == "TRUE",
                               true = "Shaggy",
                               false = "0")) |>
  mutate(captured_scooby = as.factor(captured_scooby)) |>
  mutate(captured_scooby = if_else(captured_scooby == "TRUE",
                               true = "Scooby",
                               false = "0")) |>
  pivot_longer(cols = (5:9), names_to = "who", values_to = "captured_by") |>
  separate(col = who, into = c("captured", "who"), sep = "_") |>
  mutate(captured_by = if_else(captured_by!=0, 1, 0))

unmasked_df <- df |> select(1:4, 15:19, 25:31, 36) |> 
  mutate(unmask_fred = as.factor(unmask_fred)) |>
  mutate(unmask_fred = if_else(unmask_fred == "TRUE",
                               true = "Fred",
                               false = "0")) |>
  mutate(unmask_daphnie = as.factor(unmask_daphnie)) |>
  mutate(unmask_daphnie = if_else(unmask_daphnie == "TRUE",
                               true = "Daphnie",
                               false = "0")) |>
  mutate(unmask_velma = as.factor(unmask_velma)) |>
  mutate(unmask_velma = if_else(unmask_velma == "TRUE",
                               true = "Velma",
                               false = "0")) |>
  mutate(unmask_shaggy = as.factor(unmask_shaggy)) |>
  mutate(unmask_shaggy = if_else(unmask_shaggy == "TRUE",
                               true = "Shaggy",
                               false = "0")) |>
  mutate(unmask_scooby = as.factor(unmask_scooby)) |>
  mutate(unmask_scooby = if_else(unmask_scooby == "TRUE",
                               true = "Scooby",
                               false = "0")) |>
  mutate(unmask_other = as.factor(unmask_other)) |>
  mutate(unmask_other = if_else(unmask_other == "TRUE",
                               true = "Other",
                               false = "0")) |>
  pivot_longer(cols = (5:10), names_to = "who", values_to = "unmasked") |>
  separate(col = who, into = c("unmasked_by", "who"), sep = "_") |>
  mutate(unmasked = if_else(unmasked!=0, 1, 0))

snacks_df <- df |> select(1:4, 20:24, 26:31, 36) |> 
  mutate(snack_fred = as.factor(snack_fred)) |>
  mutate(snack_fred = if_else(snack_fred == "TRUE",
                               true = "Fred",
                               false = "0")) |>
  mutate(snack_daphnie = as.factor(snack_daphnie)) |>
  mutate(snack_daphnie = if_else(snack_daphnie == "TRUE",
                               true = "Daphnie",
                               false = "0")) |>
  mutate(snack_velma = as.factor(snack_velma)) |>
  mutate(snack_velma = if_else(snack_velma == "TRUE",
                               true = "Velma",
                               false = "0")) |>
  mutate(snack_shaggy = as.factor(snack_shaggy)) |>
  mutate(snack_shaggy = if_else(snack_shaggy == "TRUE",
                               true = "Shaggy",
                               false = "0")) |>
  mutate(snack_scooby = as.factor(snack_scooby)) |>
  mutate(snack_scooby = if_else(snack_scooby == "TRUE",
                               true = "Scooby",
                               false = "0")) |>
  pivot_longer(cols = (5:9), names_to = "who", values_to = "snacks") |>
  separate(col = who, into = c("snack", "who"), sep = "_") |>
  mutate(snacks = if_else(snacks!=0, 1, 0))

catchphrase_df <- df |> select(1:4, 32:35, 26:31, 36) |>
  pivot_longer(cols = (5:8), names_to = "catchphrase", values_to = "Count") |>
  mutate(Count = as.factor(Count)) |>
  mutate(Count = fct_recode(Count, "0" = "NULL")) |>
  mutate(Count = as.numeric(as.character(Count))) 
library(plotly)
```

## Data Introduction

* Scooby-Doo dataset from tidyTuesday

* Goal: which characters catches, captures, unmasks, says their catchphrase, and snacks the most

* Made a shiny app to be able to filter by variable, series, and characteristics of the investigation

## Visualization 1: Snacks

```{r}
snacks_df |> group_by(who) |> summarise(count = sum(snacks)) |>
  ggplot(aes(x = who, y = count)) +
  geom_col(position = "dodge", fill = c("#7c68ae", "#76a2ca",
                                        "#B87333","#b2bb1b", "#F8991D")) +
  labs(title = "Snack count by character for What's New Scooby Doo") +
  theme_minimal(base_size = 20)
```

## Visualization 1: Snacks

```{r}
snacks_plot <- snacks_df|> group_by(who, series_name) |> 
  summarise(count = sum(snacks)) |>
  ggplot(aes(x = who, y = count, label = series_name)) +
  geom_jitter(width = 0.1, aes(color = who)) +
  scale_color_manual(values = c("daphnie" = "#7c68ae",
                                "fred" = "#76a2ca",
                                "scooby" = "#B87333",
                                "shaggy" = "#b2bb1b",
                                "velma" = "#F8991D")) +
  theme_minimal(base_size = 20) +
  labs(title = "Snack Count by Character", x = "Character", y = "Number of Snacks")
ggplotly(snacks_plot, tooltip = "label") |> style(showlegend = FALSE)
```

## Visualization 2

```{r}

```
